name: fiuba-reviews
services:
  base-de-datos:
    build:
      context: ./crates/adaptador-datos
      args:
        HF_INFERENCE_API_KEY: $HF_INFERENCE_API_KEY
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
