name: fiuba-reviews
services:
  base-de-datos:
    build:
      context: ./crates/adaptador-datos
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  generador-descripciones:
    build:
      context: ./crates/generador-descripciones
    environment:
      DATABASE_URL: $DATABASE_URL
      HF_INFERENCE_API_KEY: $HF_INFERENCE_API_KEY
      RUST_LOG: generador_descripciones=info,sqlx=error
      WAIT_HOSTS: base-de-datos:5432
      WAIT_LOGGER_LEVEL: error
      WAIT_SLEEP_INTERVAL: 5
      WAIT_TIMEOUT: 180
    restart: no
