name: "fiuba-reviews"
services:
  backend:
    build: ./backend
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "5000:5000"

  database:
    build: ./database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
