services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
  database:
    build: ./database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
      
