name: fiuba-reviews
services:
  generador-descripciones:
    build:
      context: ./crates/generador-descripciones
    depends_on:
      base-de-datos:
        condition: service_healthy

  base-de-datos:
    build:
      context: ./crates/adaptador-datos
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
