name: "fiuba-reviews"
services:
  backend:
    build: ./backend
    environment:
      BACKEND_PORT: $BACKEND_PORT
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432
      WAIT_HOSTS: database:5432
    restart: always
    depends_on:
      database:
        condition: service_healthy
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}

  database:
    build: ./adaptador_datos
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
